version: "3"
services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin#123
      MYSQL_USER: admin
      MYSQL_DATABASE: mydatabase
      MYSQL_PASSWORD: admin#123
  backend:
    build: ./server
    deploy:
      replicas: 3
    ports:
      - "5000"
    environment:
      - DB_HOST=database-1.ctyigwe2yzsx.us-east-2.rds.amazonaws.com
      - DB_USER=admin
      - DB_NAME=mydatabase
      - DB_PASSWORD=admin#123
    depends_on:
      - database
  frontend:
    build: ./client
    deploy:
      replicas: 3
    ports:
      - "80"
    depends_on:
      - backend
